"""Plain-language RU/EN copy for analytical panels."""

from app.i18n import analytics_tr

TEXT = {
    "validation_intro": ("Проверка на истории, которую модель не видела при обучении.", "Evaluation on history withheld from model training."),
    "validation_period_plain": ("{period} · ежедневные прогнозы: {issues}", "{period} · daily forecasts: {issues}"),
    "walk_forward": ("Каждый месяц модель обучена только на более ранних данных.", "For each month, the model is trained only on earlier data."),
    "skill_headline": ("Ошибка прогноза на сутки вперёд {climate} климатологии и {persistence} инерционного прогноза.", "Day-ahead error is {climate} climatology and {persistence} persistence."),
    "lower": ("на {value}% ниже", "{value}% lower than"),
    "higher": ("на {value}% выше", "{value}% higher than"),
    "headline_mae": ("Средняя ошибка на завтра", "Day-ahead mean error"),
    "headline_baseline": ("Климатология: {value} мощности", "Climatology: {value} of capacity"),
    "headline_skill": ("Лучше климатологии", "Improvement over climatology"),
    "headline_coverage": ("Покрытие после калибровки", "Coverage after calibration"),
    "headline_raw_coverage": ("Покрытие до калибровки", "Coverage before calibration"),
    "calibration_check": ("Независимая проверка: {month}", "Held-out check: {month}"),
    "calibration_fit": ("Калибровка настроена на {months}.", "Calibration fitted on {months}."),
    "coverage_before_all": ("До калибровки за весь период валидации: {value}.", "Before calibration across the full validation period: {value}."),
    "coverage_before_check": ("До калибровки на том же отложенном месяце: {value}.", "Before calibration on the same held-out month: {value}."),
    "coverage_target": ("Номинальное покрытие P10–P90 — 80%: столько фактических значений ожидается внутри диапазона.", "The nominal P10–P90 coverage is 80%: this is the expected share of observations inside the interval."),
    "nowcast_title": ("Сегодня: поправка по свежим данным SCADA", "Intraday: correction using recent SCADA"),
    "nowcast_mae": ("Средняя ошибка с поправкой", "Mean error with correction"),
    "nowcast_note": ("Без поправки: {value} мощности. Поправка использует только измерения, доступные на момент выпуска.", "Without correction: {value} of capacity. The correction uses only observations available at issue time."),
    "comparison": ("Наша модель и простые альтернативы", "Our model and simple alternatives"),
    "model": ("WindAgent (наша модель)", "WindAgent (our model)"),
    "model_with_nowcast": ("WindAgent + поправка SCADA", "WindAgent + SCADA correction"),
    "persistence": ("Как сейчас (последний час)", "Latest measured hour"),
    "climatology": ("Среднее за месяц и час", "Average by month and hour"),
    "nwp_powercurve": ("Только кривая мощности по погоде", "Weather power curve only"),
    "chart_model": ("WindAgent", "WindAgent"),
    "chart_persistence": ("Последний час", "Latest hour"),
    "chart_climatology": ("Климатология", "Climatology"),
    "chart_nwp_powercurve": ("Кривая мощности", "Power curve"),
    "table_mae": ("Средняя ошибка, % мощности", "Mean error, % of capacity"),
    "table_rmse": ("Крупные ошибки (RMSE), %", "Large errors (RMSE), %"),
    "table_bias": ("Смещение, %", "Bias, %"),
    "table_n": ("Часов", "Hours"),
    "table_skill": ("Наша модель лучше на", "Our model improves by"),
    "table_skill_note": ("Сравнение с WindAgent без поправки SCADA в том же продукте: 1 − MAE WindAgent / MAE альтернативы. Отрицательное значение означает, что альтернатива лучше.", "Comparison with uncorrected WindAgent for the same product: 1 − WindAgent MAE / alternative MAE. A negative value means the alternative is better."),
    "baseline_climatology": ("Климатология — среднее для месяца и часа, рассчитанное только по обучающей истории.", "Climatology is the average for the month and hour, calculated from training history only."),
    "lead_axis": ("Горизонт прогноза, ч", "Forecast horizon, hours"),
    "mae_axis": ("Средняя ошибка, % мощности", "Mean error, % of capacity"),
    "width": ("Ширина интервала до калибровки", "Interval width before calibration"),
    "loto_mae": ("Ошибка на другой турбине", "Error on held-out turbine"),
    "loto_reference": ("Ошибка при обучении на обеих", "Error when trained on both"),
    "submission_headline": ("{period}: прогнозов на сутки вперёд — {issues}, часов — {hours}. Это файл сабмита.", "{period}: {issues} day-ahead forecasts, {hours} hours. This is the submission file."),
    "submission_intro": ("Первичные прогнозы на сутки вперёд. На графике мощность показана в процентах от номинала.", "Initial day-ahead forecasts. The chart shows power as a percentage of rated capacity."),
    "download_submission_primary": ("Скачать сабмит ({hours} ч, CSV)", "Download submission ({hours} h, CSV)"),
    "power_axis": ("Мощность, % от номинала", "Power, % of rated capacity"),
    "energy_title_period": ("Ожидаемая выработка по дням · {period}", "Expected daily generation · {period}"),
    "energy_axis": ("Часы работы на полной мощности", "Equivalent full-power hours"),
    "energy_note": ("Ожидаемые часы работы на полной мощности: сумма почасовой нормированной мощности. Показаны только полные сутки; это не МВт·ч.", "Equivalent full-power hours: the sum of hourly normalized power. Only complete days are shown; this is not MWh."),
    "revision_note": ("Насколько уточнение изменило прогноз: красный — вверх, синий — вниз.", "How the update changed the forecast: red means higher, blue means lower."),
    "revision_grid_note": ("Строка — выпуск прогноза; столбец — число часов после выпуска, а не время суток. Белый цвет означает отсутствие изменения, пустая ячейка — нет сопоставленной пары.", "Each row is a forecast issue; columns are hours since issue, not clock hours. White means unchanged; an empty cell means no matched pair."),
    "revision_elapsed": ("Первые {hours} ч к моменту уточнения уже прошли — их не пересчитывают.", "The first {hours} hours had already elapsed when the update was issued, so they are not recomputed."),
    "revision_elapsed_generic": ("Уточнение пересчитывает только оставшиеся часы: прошедшие часы не меняются.", "Updates recompute only remaining hours; elapsed hours are not revised."),
    "revision_issue_axis": ("Выпуск · {clock}", "Issue · {clock}"),
    "revision_delta": ("Изменение, % мощности", "Change, % of capacity"),
    "revision_hover": ("Выпуск %{{y}}<br>Через %{{x}} ч<br>%{{z:+.1%}}<extra></extra>", "Issue %{{y}}<br>Lead %{{x}} h<br>%{{z:+.1%}}<extra></extra>"),
    "how_intro": ("Пять шагов от доступного прогноза погоды до прогноза выработки.", "Five steps from an available weather forecast to expected power generation."),
    "how_step_weather": ("Берём прогнозы погоды, опубликованные до {hour}", "Take weather forecasts published before {hour}"),
    "how_step_validate": ("Проверяем полноту и качество входных данных", "Check input completeness and quality"),
    "how_step_model": ("ML-модель переводит ветер в мощность", "The ML model converts wind into power"),
    "how_step_publish": ("Публикуем почасовой прогноз на {hours} ч с диапазоном P10–P90", "Publish a {hours}-hour forecast with a P10–P90 interval"),
    "how_step_update": ("Проверяем новые погодные расчёты и при необходимости уточняем прогноз", "Check newer weather runs and update the forecast when needed"),
    "how_step_update_timed": ("Через {hours} ч проверяем новые погодные расчёты и при необходимости уточняем прогноз", "After {hours} hours, check newer weather runs and update when needed"),
    "how_clock": ("Время выпуска указано по часам данных.", "Issue time uses the data clock."),
    "asof_title": ("Почему нет подглядывания в будущее", "Why there is no look-ahead"),
    "asof_rule": ("Погодный расчёт можно использовать, только когда начало расчёта плюс задержка публикации не позже момента выпуска прогноза. Фактическую будущую погоду не подставляем, а при уточнении учитываем только расчёты, уже доступные на новый момент.", "A weather run can be used only when its initialization plus publication delay is no later than forecast issue time. Future observed weather is never substituted, and revisions use only runs already available at the new as-of time."),
    "clock_title": ("Два часовых пояса — один момент", "Two time zones, one instant"),
    "run_locally_title": ("Запустить у себя", "Run locally"),
    "run_locally_note": ("Сайт — демонстрация. Проверить и воспроизвести решение можно из репозитория; ключ LLM не обязателен.", "This website is a demo. Verify and reproduce the solution from the repository; an LLM key is optional."),
    "run_install": ("1. Установить зависимости", "1. Install dependencies"),
    "run_verify": ("2. Проверить решение — ожидается 4 × PASS", "2. Verify the solution — expect 4 × PASS"),
    "run_forecast": ("3. Воспроизвести первый выпуск офлайн", "3. Reproduce the first issue offline"),
    "run_dashboard": ("4. Открыть дашборд", "4. Open the dashboard"),
    "run_docker": ("Или запустить через Docker", "Or start with Docker"),
    "run_context": ("Выполняйте команды из папки репозитория с подготовленными данными и кэшем погоды. Инструкции по окружению — README, разделы 7–8.", "Run these commands from the repository folder with the prepared data and weather cache. Environment setup is in README sections 7–8."),
}

MONTHS = {
    "RU": ["январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"],
    "EN": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
}


def tr(key: str, lang: str = "RU", **values) -> str:
    if key not in TEXT:
        return analytics_tr(key, lang, **values)
    return TEXT[key][1 if str(lang).upper() == "EN" else 0].format(**values)
